apiVersion: v2
name: stock-pulse
description: StockPulse – Real-time stock analysis platform (Next.js)
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - stock
  - finance
  - nextjs
maintainers:
  - name: uttam-gohil
    email: upgohil2925@gmail.com
