replicaCount: 5

image:
  repository: jupiter000/stock-pulse
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "sha-8d0b5e6"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    # Rate limit: Max 2 requests per second per IP
    # nginx.ingress.kubernetes.io/limit-rps: "2"
    # nginx.ingress.kubernetes.io/limit-burst-multiplier: "1"
    
    nginx.ingress.kubernetes.io/limit-rpm: "20"

  hosts:
    - host: stock-pulse.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
