apiVersion: v1
kind: Service
metadata:
  name: {{ include "stock-pulse.fullname" . }}-active
  labels:
    {{- include "stock-pulse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  # The Rollout controller automatically updates this selector to point to the active ReplicaSet
  selector:
    {{- include "stock-pulse.selectorLabels" . | nindent 4 }}
