apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stock-pulse
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ItsJupiter000/gitops.git # <-- UPDATE THIS
    targetRevision: main
    path: helm/stock-pulse
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
